<?php
session_start();
require_once 'config/database.php';
require_once 'includes/functions.php';

require_login();

$user = get_user_data($_SESSION['user_id']);
$countdown = get_anniversary_countdown();
$quote = get_random_quote();
$current_date = date('F j, Y');
$current_time = date('H:i:s');

// Get recent to-do items
$database = new Database();
$db = $database->getConnection();
$query = "SELECT * FROM todo_items WHERE user_id = :user_id AND is_completed = 0 ORDER BY position_order ASC LIMIT 5";
$stmt = $db->prepare($query);
$stmt->bindParam(':user_id', $_SESSION['user_id']);
$stmt->execute();
$todo_items = $stmt->fetchAll(PDO::FETCH_ASSOC);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - Our Secret Place</title>
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>
    <?php include 'includes/navbar.php'; ?>
    
    <main class="main-content">
        <div class="home-container">
            <!-- Greeting Section -->
            <div class="greeting-section">
                <h1>Hi, <a href="profile.php" class="user-link"><?php echo htmlspecialchars($user['name']); ?></a></h1>
                <p class="current-date"><?php echo $current_date; ?></p>
            </div>
            
            <!-- Main Dashboard -->
            <div class="dashboard-grid">
                <!-- Anniversary Countdown -->
                <div class="dashboard-card countdown-card">
                    <div class="card-header">
                        <i class="fas fa-heart"></i>
                        <h3>Anniversary Countdown</h3>
                    </div>
                    <div class="countdown-display">
                        <div class="countdown-number"><?php echo $countdown; ?></div>
                        <div class="countdown-label">days until our anniversary</div>
                    </div>
                </div>
                
                <!-- Live Time -->
                <div class="dashboard-card time-card">
                    <div class="card-header">
                        <i class="fas fa-clock"></i>
                        <h3>Current Time</h3>
                    </div>
                    <div class="time-display" id="live-time">
                        <?php echo $current_time; ?>
                    </div>
                </div>
                
                <!-- Motivational Quote -->
                <div class="dashboard-card quote-card">
                    <div class="card-header">
                        <i class="fas fa-quote-left"></i>
                        <h3>Daily Inspiration</h3>
                    </div>
                    <div class="quote-content">
                        <p>"<?php echo $quote; ?>"</p>
                    </div>
                </div>
                
                <!-- Calendar -->
                <div class="dashboard-card calendar-card large-card">
                    <div class="card-header">
                        <i class="fas fa-calendar"></i>
                        <h3>Calendar</h3>
                    </div>
                    <div class="calendar-widget" id="calendar-widget">
                        <!-- Calendar will be generated by JavaScript -->
                    </div>
                </div>
                
                <!-- To-Do List -->
                <div class="dashboard-card todo-card">
                    <div class="card-header">
                        <i class="fas fa-tasks"></i>
                        <h3>Quick To-Do</h3>
                        <a href="tools.php" class="view-all">View All</a>
                    </div>
                    <div class="todo-list">
                        <?php if (empty($todo_items)): ?>
                            <p class="no-todos">No pending tasks</p>
                        <?php else: ?>
                            <?php foreach ($todo_items as $item): ?>
                                <div class="todo-item">
                                    <span class="todo-text"><?php echo htmlspecialchars($item['title']); ?></span>
                                    <span class="todo-category"><?php echo $item['category']; ?></span>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>
                
                <!-- Photo Placeholder -->
                <div class="dashboard-card photo-card">
                    <div class="card-header">
                        <i class="fas fa-camera"></i>
                        <h3>Photo of the Day</h3>
                    </div>
                    <div class="photo-placeholder">
                        <i class="fas fa-image"></i>
                        <p>Photo placeholder</p>
                    </div>
                </div>
            </div>
        </div>
    </main>
    
    <script src="assets/js/main.js"></script>
    <script src="assets/js/calendar.js"></script>
</body>
</html>
